const ActionNames = {
  FETCH_WORDS_REQUEST: "FETCH_WORDS_REQUEST",
  FETCH_WORDS_SUCCESS: "FETCH_WORDS_SUCCESS",
  FETCH_WORDS_FAILURE: "FETCH_WORDS_FAILURE",

  ADD_WORDS_REQUEST: "ADD_WORDS_REQUEST",
  ADD_WORDS_SUCCESS: "ADD_WORDS_SUCCESS",
  ADD_WORDS_FAILURE: "ADD_WORDS_FAILURE",

  DELETE_WORDS_REQUEST: "DELETE_WORDS_REQUEST",
  DELETE_WORDS_SUCCESS: "DELETE_WORDS_SUCCESS",
  DELETE_WORDS_FAILURE: "DELETE_WORDS_FAILURE",

  FETCH_LANGUAGES_REQUEST: "FETCH_LANGUAGES_REQUEST",
  FETCH_LANGUAGES_SUCCESS: "FETCH_LANGUAGES_SUCCESS",
  FETCH_LANGUAGES_FAILURE: "FETCH_LANGUAGES_FAILURE",

  ADD_LANGUAGE_REQUEST: "ADD_LANGUAGE_REQUEST",
  ADD_LANGUAGE_SUCCESS: "ADD_LANGUAGE_SUCCESS",
  ADD_LANGUAGE_FAILURE: "ADD_LANGUAGE_FAILURE",

  DELETE_LANGUAGE_REQUEST: "DELETE_LANGUAGE_REQUEST",
  DELETE_LANGUAGE_SUCCESS: "DELETE_LANGUAGE_SUCCESS",
  DELETE_LANGUAGE_FAILURE: "DELETE_LANGUAGE_FAILURE",

  FETCH_ACTIVE_LANGUAGES_REQUEST: "FETCH_ACTIVE_LANGUAGES_REQUEST",
  FETCH_ACTIVE_LANGUAGES_SUCCESS: "FETCH_ACTIVE_LANGUAGES_SUCCESS",
  FETCH_ACTIVE_LANGUAGES_FAILURE: "FETCH_ACTIVE_LANGUAGES_FAILURE",

  ADD_ACTIVE_LANGUAGE_REQUEST: "ADD_ACTIVE_LANGUAGE_REQUEST",
  ADD_ACTIVE_LANGUAGE_SUCCESS: "ADD_ACTIVE_LANGUAGE_SUCCESS",
  ADD_ACTIVE_LANGUAGE_FAILURE: "ADD_ACTIVE_LANGUAGE_FAILURE",

  UPDATE_ACTIVE_LANGUAGES_REQUEST: "UPDATE_ACTIVE_LANGUAGES_REQUEST",
  UPDATE_ACTIVE_LANGUAGES_SUCCESS: "UPDATE_ACTIVE_LANGUAGES_SUCCESS",
  UPDATE_ACTIVE_LANGUAGES_FAILURE: "UPDATE_ACTIVE_LANGUAGES_FAILURE",

  DELETE_ACTIVE_LANGUAGES_REQUEST: "DELETE_ACTIVE_LANGUAGES_REQUEST",
  DELETE_ACTIVE_LANGUAGES_SUCCESS: "DELETE_ACTIVE_LANGUAGES_SUCCESS",
  DELETE_ACTIVE_LANGUAGES_FAILURE: "DELETE_ACTIVE_LANGUAGES_FAILURE",

  ADD_PHOTO_REQUEST: "ADD_PHOTO_REQUEST",
  ADD_PHOTO_SUCCESS: "ADD_PHOTO_SUCCESS",
  ADD_PHOTO_FAILURE: "ADD_PHOTO_FAILURE",

  FETCH_PHOTOS_REQUEST: "FETCH_PHOTOS_REQUEST",
  FETCH_PHOTOS_SUCCESS: "FETCH_PHOTOS_SUCCESS",
  FETCH_PHOTOS_FAILURE: "FETCH_PHOTOS_FAILURE",

  DELETE_PHOTO_REQUEST: "DELETE_PHOTO_REQUEST",
  DELETE_PHOTO_SUCCESS: "DELETE_PHOTO_SUCCESS",
  DELETE_PHOTO_FAILURE: "DELETE_PHOTO_FAILURE",

  ADD_TEXTS_REQUEST: "ADD_TEXTS_REQUEST",
  ADD_TEXTS_SUCCESS: "ADD_TEXTS_SUCCESS",
  ADD_TEXTS_FAILURE: "ADD_TEXTS_FAILURE",

  FETCH_TEXTS_REQUEST: "FETCH_TEXTS_REQUEST",
  FETCH_TEXTS_SUCCESS: "FETCH_TEXTS_SUCCESS",
  FETCH_TEXTS_FAILURE: "FETCH_TEXTS_FAILURE",

  DELETE_TEXTS_REQUEST: "DELETE_TEXTS_REQUEST",
  DELETE_TEXTS_SUCCESS: "DELETE_TEXTS_SUCCESS",
  DELETE_TEXTS_FAILURE: "DELETE_TEXTS_FAILURE",

  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",

  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",

  UPDATE_LANGUAGE_REQUEST: "UPDATE_LANGUAGE_REQUEST",
  UPDATE_LANGUAGE_SUCCESS: "UPDATE_LANGUAGE_SUCCESS",
  UPDATE_LANGUAGE_FAILURE: "UPDATE_LANGUAGE_FAILURE",

  UPDATE_WORDS_REQUEST: "UPDATE_WORDS_REQUEST",
  UPDATE_WORDS_SUCCESS: "UPDATE_WORDS_SUCCESS",
  UPDATE_WORDS_FAILURE: "UPDATE_WORDS_FAILURE",

  UPDATE_PHOTO_REQUEST: "UPDATE_PHOTO_REQUEST",
  UPDATE_PHOTO_SUCCESS: "UPDATE_PHOTO_SUCCESS",
  UPDATE_PHOTO_FAILURE: "UPDATE_PHOTO_FAILURE",

  UPDATE_TEXTS_REQUEST: "UPDATE_TEXTS_REQUEST",
  UPDATE_TEXTS_SUCCESS: "UPDATE_TEXTS_SUCCESS",
  UPDATE_TEXTS_FAILURE: "UPDATE_TEXTS_FAILURE",

  SIGNUP_REQUEST: "SIGNUP_REQUEST",
  SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
  SIGNUP_FAILURE: "SIGNUP_FAILURE",
};

export default ActionNames;
